max_threads: 4
raw_nanopore_data: "seq6_nikita_fungiITS/seq6/20260605_1339_MN48615_axh386_c53dccc6"

#source https://nanoporetech.com/document/chemistry-technical-document
adapters:
  "top": "TTTTTTTTCCTGTACTTCGTTCAGTTACGTATTGCT"
  "top-core": "CCTGTACTTCGTTCAGTTACGTATTGCT"
  "bottom": "ACGTAACTGAACGAAGTACAGG"

#source https://benlangmead.github.io/aws-indexes/k2
kraken_db: https://genome-idx.s3.amazonaws.com/kraken/k2_pluspf_16_GB_20260226.tar.gz

data:
  base_root: "data"
  dirs:
    raw: "raw"
    barcodes: 'merged_barcodes'
    references: "references"
    trimmed_barcodes: 'trimmed_barcodes'
    trimmed_adapters: "trimmed_adapters"
    trimmed_primers: "trimmed_primers"
    filtered_barcodes: "filtered_barcodes"
    kraken_db: "kraken_db"


workflow:
  base_root: "workflow"
  dirs:
    rules: "rules"
    scripts: "scripts"
    lib: "lib"
    envs: 'envs'
    external: 'external'

qc:
  base_root: 'QC'
  dirs:
    seq_stats: 'seq_stats'
    trimming_reports: 'trimming_reports'
    fa2tsv: 'contamination/length'
    locate: 'contamination/hits'
    joins: "contamination/joins"
    contamination_plots: "contamination/plots"
    nanoplots: "nanoplots"

output:
  base_root: "output"
  dirs:
    amplicon_sort: 'amplicon_consensus'
    amplicons_classification: 'amplicons_classification'
    adjusted_kraken_reports: 'adjusted_reports'
